# Generated by Django 6.0.4 on 2026-04-24 03:56

import django.contrib.postgres.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogacion', '0002_initial'),
        ('fotografias', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fotografia',
            options={'ordering': ['-fecha_registro'], 'verbose_name': 'Fotografía / Imagen', 'verbose_name_plural': 'Fotografías / Imágenes'},
        ),
        migrations.RemoveField(
            model_name='fotografia',
            name='alto_fisico_cm',
        ),
        migrations.RemoveField(
            model_name='fotografia',
            name='ancho_fisico_cm',
        ),
        migrations.RemoveField(
            model_name='fotografia',
            name='dimensiones_fisicas_texto',
        ),
        migrations.RemoveField(
            model_name='fotografia',
            name='es_blanco_negro',
        ),
        migrations.RemoveField(
            model_name='fotografia',
            name='es_color',
        ),
        migrations.RemoveField(
            model_name='fotografia',
            name='es_sepia',
        ),
        migrations.RemoveField(
            model_name='fotografia',
            name='imagen_aerea',
        ),
        migrations.RemoveField(
            model_name='fotografia',
            name='origen_fuente',
        ),
        migrations.RemoveField(
            model_name='fotografia',
            name='relacion_estetica',
        ),
        migrations.RemoveField(
            model_name='fotografia',
            name='relacion_interpretacion',
        ),
        migrations.RemoveField(
            model_name='fotografia',
            name='relacion_organizacion',
        ),
        migrations.RemoveField(
            model_name='fotografia',
            name='relacion_representativa',
        ),
        migrations.RemoveField(
            model_name='fotografia',
            name='relacion_transformacion',
        ),
        migrations.RemoveField(
            model_name='fotografia',
            name='tiene_alteracion_color',
        ),
        migrations.RemoveField(
            model_name='fotografia',
            name='tipo_imagen_formal',
        ),
        migrations.RemoveField(
            model_name='fotografia',
            name='tipo_imagen_manual',
        ),
        migrations.RemoveField(
            model_name='fotografia',
            name='tipo_imagen_material',
        ),
        migrations.RemoveField(
            model_name='fotografia',
            name='tipo_imagen_tecnica',
        ),
        migrations.RemoveField(
            model_name='fotografia',
            name='url_promocion',
        ),
        migrations.RemoveField(
            model_name='fotografia',
            name='uso_apoyo_visual',
        ),
        migrations.RemoveField(
            model_name='fotografia',
            name='uso_pedagogico',
        ),
        migrations.RemoveField(
            model_name='fotografia',
            name='uso_promocion',
        ),
        migrations.AddField(
            model_name='fotografia',
            name='alto_fisico_px',
            field=models.IntegerField(blank=True, null=True, verbose_name='Alto físico (px)'),
        ),
        migrations.AddField(
            model_name='fotografia',
            name='ancho_fisico_px',
            field=models.IntegerField(blank=True, null=True, verbose_name='Ancho físico (px)'),
        ),
        migrations.AddField(
            model_name='fotografia',
            name='caracteristicas',
            field=models.CharField(blank=True, choices=[('Color', 'Color'), ('Blanco y negro', 'Blanco y negro'), ('Sepia', 'Sepia'), ('Alteración color', 'Alteración color')], max_length=50, null=True, verbose_name='Características'),
        ),
        migrations.AddField(
            model_name='fotografia',
            name='descripcion_imagen_propia',
            field=models.TextField(blank=True, null=True, verbose_name='Descripción de imagen propia'),
        ),
        migrations.AddField(
            model_name='fotografia',
            name='explicacion_funcion',
            field=models.TextField(blank=True, null=True, verbose_name='Explicación de la función'),
        ),
        migrations.AddField(
            model_name='fotografia',
            name='imagen_propia',
            field=models.ImageField(blank=True, null=True, upload_to='fotos/extras/', verbose_name='Imagen propia'),
        ),
        migrations.AddField(
            model_name='fotografia',
            name='publicacion_imagen',
            field=models.TextField(blank=True, null=True, verbose_name='Publicación de la imagen'),
        ),
        migrations.AddField(
            model_name='fotografia',
            name='relaciones',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('Estéticas', 'Estéticas'), ('Representativas', 'Representativas'), ('Transformación', 'Transformación'), ('Organización', 'Organización'), ('Interpretación', 'Interpretación')], max_length=50), blank=True, null=True, verbose_name='Relaciones'),
        ),
        migrations.AddField(
            model_name='fotografia',
            name='tipo_imagen',
            field=models.CharField(blank=True, choices=[('Manual', 'Manual'), ('Técnica', 'Técnica'), ('Formal', 'Formal'), ('Material', 'Material')], max_length=50, null=True, verbose_name='Tipo de imagen'),
        ),
        migrations.AddField(
            model_name='fotografia',
            name='uso_imagen',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('Pedagógico', 'Pedagógico'), ('Apoyo visual', 'Apoyo visual'), ('Promoción', 'Promoción')], max_length=50), blank=True, null=True, verbose_name='Uso imagen'),
        ),
        migrations.AlterField(
            model_name='fotografia',
            name='acuerdo_contexto',
            field=models.CharField(blank=True, choices=[('0-30', '0-30'), ('30-60', '30-60'), ('60-90', '60-90'), ('100', '100')], max_length=10, null=True, verbose_name='Acuerdo al contexto (%)'),
        ),
        migrations.AlterField(
            model_name='fotografia',
            name='adapta_lenguaje',
            field=models.CharField(blank=True, choices=[('0-30', '0-30'), ('30-60', '30-60'), ('60-90', '60-90'), ('100', '100')], max_length=10, null=True, verbose_name='Adapta el lenguaje (%)'),
        ),
        migrations.AlterField(
            model_name='fotografia',
            name='alto_pixeles',
            field=models.IntegerField(blank=True, null=True, verbose_name='Alto digital (px)'),
        ),
        migrations.AlterField(
            model_name='fotografia',
            name='ancho_pixeles',
            field=models.IntegerField(blank=True, null=True, verbose_name='Ancho digital (px)'),
        ),
        migrations.AlterField(
            model_name='fotografia',
            name='anotaciones',
            field=models.TextField(blank=True, null=True, verbose_name='Anotaciones sobre la imagen'),
        ),
        migrations.AlterField(
            model_name='fotografia',
            name='archivo_imagen',
            field=models.ImageField(upload_to='fotos/principal/', verbose_name='Archivo de imagen'),
        ),
        migrations.AlterField(
            model_name='fotografia',
            name='autor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalogacion.autor', verbose_name='Autor de la imagen'),
        ),
        migrations.AlterField(
            model_name='fotografia',
            name='conceptos_imagen',
            field=models.TextField(blank=True, null=True, verbose_name='Concepto(s) imagen'),
        ),
        migrations.AlterField(
            model_name='fotografia',
            name='condiciones_uso',
            field=models.TextField(blank=True, null=True, verbose_name='Condiciones de uso'),
        ),
        migrations.AlterField(
            model_name='fotografia',
            name='contexto_figura',
            field=models.TextField(blank=True, null=True, verbose_name='Figura'),
        ),
        migrations.AlterField(
            model_name='fotografia',
            name='contexto_fondo',
            field=models.TextField(blank=True, null=True, verbose_name='Fondo'),
        ),
        migrations.AlterField(
            model_name='fotografia',
            name='descripcion_general',
            field=models.TextField(verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='fotografia',
            name='elementos_distraccion',
            field=models.CharField(blank=True, choices=[('0-30', '0-30'), ('30-60', '30-60'), ('60-90', '60-90'), ('100', '100')], max_length=10, null=True, verbose_name='Elementos de distracción (%)'),
        ),
        migrations.AlterField(
            model_name='fotografia',
            name='elementos_visuales_importantes',
            field=models.TextField(blank=True, null=True, verbose_name='Elementos visuales más importantes'),
        ),
        migrations.AlterField(
            model_name='fotografia',
            name='entidad_responsable',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalogacion.entidad', verbose_name='Entidad responsable de la imagen'),
        ),
        migrations.AlterField(
            model_name='fotografia',
            name='fecha_produccion',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Fecha de producción'),
        ),
        migrations.AlterField(
            model_name='fotografia',
            name='fecha_publicacion',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Fecha de publicación'),
        ),
        migrations.AlterField(
            model_name='fotografia',
            name='formato_actual',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Formato actual'),
        ),
        migrations.AlterField(
            model_name='fotografia',
            name='formato_original',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Formato original'),
        ),
        migrations.AlterField(
            model_name='fotografia',
            name='imagen_mapa',
            field=models.ImageField(blank=True, null=True, upload_to='fotos/mapas/', verbose_name='Imagen de mapa desde arriba'),
        ),
        migrations.AlterField(
            model_name='fotografia',
            name='legibilidad',
            field=models.CharField(blank=True, choices=[('0-30', '0-30'), ('30-60', '30-60'), ('60-90', '60-90'), ('100', '100')], max_length=10, null=True, verbose_name='Legibilidad (%)'),
        ),
        migrations.AlterField(
            model_name='fotografia',
            name='porcentaje_distorsion',
            field=models.CharField(blank=True, choices=[('Bajo', 'Bajo'), ('Medio', 'Medio'), ('Alto', 'Alto')], max_length=10, null=True, verbose_name='% Distorsión'),
        ),
        migrations.AlterField(
            model_name='fotografia',
            name='porcentaje_pixelacion',
            field=models.CharField(blank=True, choices=[('Bajo', 'Bajo'), ('Medio', 'Medio'), ('Alto', 'Alto')], max_length=10, null=True, verbose_name='% Pixelación'),
        ),
        migrations.AlterField(
            model_name='fotografia',
            name='primera_version_imagen',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Primera versión'),
        ),
        migrations.AlterField(
            model_name='fotografia',
            name='profundidad_bits',
            field=models.IntegerField(blank=True, null=True, verbose_name='Profundidad bits'),
        ),
        migrations.AlterField(
            model_name='fotografia',
            name='resolucion_horizontal',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Resolución horizontal (ppp)'),
        ),
        migrations.AlterField(
            model_name='fotografia',
            name='resolucion_vertical',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Resolución vertical (ppp)'),
        ),
        migrations.AlterField(
            model_name='fotografia',
            name='respeta_esquemas_culturales',
            field=models.CharField(blank=True, choices=[('0-30', '0-30'), ('30-60', '30-60'), ('60-90', '60-90'), ('100', '100')], max_length=10, null=True, verbose_name='Respeta esquemas culturales (%)'),
        ),
        migrations.AlterField(
            model_name='fotografia',
            name='rigor_cientifico',
            field=models.CharField(blank=True, choices=[('0-30', '0-30'), ('30-60', '30-60'), ('60-90', '60-90'), ('100', '100')], max_length=10, null=True, verbose_name='Rigor científico (%)'),
        ),
        migrations.AlterField(
            model_name='fotografia',
            name='simplicidad_imagen',
            field=models.CharField(blank=True, choices=[('0-30', '0-30'), ('30-60', '30-60'), ('60-90', '60-90'), ('100', '100')], max_length=10, null=True, verbose_name='Simplicidad (%)'),
        ),
        migrations.AlterField(
            model_name='fotografia',
            name='ubicacion_archivo',
            field=models.TextField(blank=True, null=True, verbose_name='Ubicación Archivo'),
        ),
        migrations.AlterField(
            model_name='fotografia',
            name='ultima_modificacion_imagen',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Última modificación'),
        ),
        migrations.AlterField(
            model_name='fotografia',
            name='unidad_resolucion',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Unidad de resolución'),
        ),
    ]
