# Generated by Django 6.0.4 on 2026-04-24 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fotografias', '0002_alter_fotografia_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fotografia',
            name='autor',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Autor de la imagen'),
        ),
        migrations.AlterField(
            model_name='fotografia',
            name='entidad_responsable',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Entidad responsable de la imagen'),
        ),
    ]
