# Generated by Django 6.0.4 on 2026-05-01 02:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colecciones', '0002_album_categoria'),
        ('fotografias', '0003_alter_fotografia_autor_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fotografia',
            name='coleccion',
        ),
        migrations.AddField(
            model_name='fotografia',
            name='album',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='colecciones.album', verbose_name='Álbum'),
        ),
        migrations.AddField(
            model_name='fotografia',
            name='vistas',
            field=models.IntegerField(default=0, verbose_name='Número de vistas'),
        ),
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField(verbose_name='Comentario')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('ip_usuario', models.GenericIPAddressField(blank=True, null=True)),
                ('fotografia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comentarios', to='fotografias.fotografia')),
            ],
            options={
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='Calificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estrellas', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')])),
                ('ip_usuario', models.GenericIPAddressField(blank=True, null=True)),
                ('fotografia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calificaciones', to='fotografias.fotografia')),
            ],
            options={
                'unique_together': {('fotografia', 'ip_usuario')},
            },
        ),
    ]
