# Generated by Django 6.0.4 on 2026-05-01 14:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colecciones', '0003_delete_coleccion_album_creado_por_and_more'),
        ('fotografias', '0004_remove_fotografia_coleccion_fotografia_album_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fotografia',
            name='album',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='colecciones.album', verbose_name='Álbum'),
        ),
        migrations.AlterField(
            model_name='fotografia',
            name='descripcion_general',
            field=models.TextField(blank=True, null=True, verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='fotografia',
            name='estado',
            field=models.CharField(blank=True, choices=[('Activo', 'Activo'), ('Revisión', 'En Revisión'), ('Archivado', 'Archivado')], default='Revisión', max_length=50, null=True, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='fotografia',
            name='funcion_imagen',
            field=models.TextField(blank=True, null=True, verbose_name='Función de la imagen'),
        ),
        migrations.AlterField(
            model_name='fotografia',
            name='idioma_original',
            field=models.CharField(blank=True, default='Español', max_length=100, null=True, verbose_name='Idioma original'),
        ),
    ]
