# Generated by Django 6.0.4 on 2026-05-01 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fotografias', '0005_alter_fotografia_album_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='comentario',
            name='nombre_usuario',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Nombre (opcional)'),
        ),
    ]
