# Generated by Django 6.0.4 on 2026-05-07 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fotografias', '0006_comentario_nombre_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='fotografia',
            name='url_fuente',
            field=models.URLField(blank=True, max_length=1000, null=True, verbose_name='URL de origen de la imagen'),
        ),
        migrations.AlterField(
            model_name='fotografia',
            name='estado',
            field=models.CharField(blank=True, choices=[('Activo', 'Activo'), ('Revisión', 'En Revisión'), ('Archivado', 'Archivado')], default='Activo', max_length=50, null=True, verbose_name='Estado'),
        ),
    ]
