# Generated by Django 6.0.4 on 2026-05-07 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fotografias', '0008_simplificar_ficha'),
    ]

    operations = [
        migrations.AddField(
            model_name='fotografia',
            name='latitud',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True, verbose_name='Latitud'),
        ),
        migrations.AddField(
            model_name='fotografia',
            name='longitud',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True, verbose_name='Longitud'),
        ),
        migrations.AlterField(
            model_name='fotografia',
            name='imagen_propia',
            field=models.ImageField(blank=True, null=True, upload_to='fotos/extras/', verbose_name='Imagen del lugar'),
        ),
        migrations.AlterField(
            model_name='fotografia',
            name='ubicacion_archivo',
            field=models.TextField(blank=True, null=True, verbose_name='Ubicación física de la fotografía'),
        ),
    ]
