# Generated by Django 6.0.4 on 2026-05-08 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fotografias', '0009_coordenadas'),
    ]

    operations = [
        migrations.AddField(
            model_name='fotografia',
            name='mapa_url',
            field=models.URLField(blank=True, max_length=1000, null=True, verbose_name='URL de Google Maps'),
        ),
    ]
