# Generated by Django 6.0.4 on 2026-05-09 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fotografias', '0010_mapa_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='fotografia',
            name='fecha_subida_original',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Fecha de subida original'),
        ),
    ]
