# Generated by Django 6.0.4 on 2026-05-30 04:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colecciones', '0003_delete_coleccion_album_creado_por_and_more'),
        ('fotografias', '0011_fecha_subida_original'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fotografia',
            name='album',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='colecciones.album', verbose_name='Álbum'),
        ),
    ]
