# Generated by Django 6.0.4 on 2026-05-01 02:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colecciones', '0002_album_categoria'),
        ('fotografias', '0004_remove_fotografia_coleccion_fotografia_album_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.DeleteModel(
            name='Coleccion',
        ),
        migrations.AddField(
            model_name='album',
            name='creado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Creado por'),
        ),
        migrations.AddField(
            model_name='categoria',
            name='categoria_padre',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subcategorias', to='colecciones.categoria', verbose_name='Categoría Padre (Dejar en blanco si es Principal)'),
        ),
        migrations.AddField(
            model_name='album',
            name='categoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='albumes', to='colecciones.categoria', verbose_name='Categoría / Subcategoría'),
        ),
    ]
