# Generated by Django 6.0.4 on 2026-04-17 05:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalogacion', '0001_initial'),
        ('fotografias', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='versionimagen',
            name='fotografia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='fotografias.fotografia'),
        ),
    ]
